{
 "title": "au-back-ui",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(ws_connections, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Messages Delay",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "messages_delay_ms{pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "WebSocket Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ws_connections{pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cpu_user{pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "cpu_system{pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Messages Dropped",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(messages_dropped{pod=~\"$pod\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "TSDB Request Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_archive_requests_bucket{pod=~\"$pod\"}[5m])) by (pod,le))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Event Loop Delay",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "event_loop_delay_main{service=\"au-back-ui\",pod=~\"$pod\"}",
     "legendFormat": "main {{pod}}"
    },
    {
     "expr": "event_loop_delay_worker{service=\"au-back-ui\",pod=~\"$pod\"}",
     "legendFormat": "worker {{pod}}"
    }
   ]
  },
  {
   "title": "Messages Processed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(messages_processed{pod=~\"$pod\"}[1m]) ",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "HTTP Archive Rows",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_archive_rows{pod=~\"$pod\"}[5m])",
     "legendFormat": "{{pod}}"
    },
    { "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "GC duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(gc_main_bucket{service=\"au-back-ui\",pod=~\"$pod\"}[5m])) by (pod,le))",
     "legendFormat": "main {{pod}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(gc_worker_bucket{service=\"au-back-ui\",pod=~\"$pod\"}[5m])) by (pod,le))",
     "legendFormat": "worker {{pod}}"
    }
   ]
  }
 ]
}