{
 "title": "au-data-quality",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "pod", "label": "Pod", "query": "label_values(errorCount, pod)" }
  ]
 },
 "panels": [
  {
   "title": "Error Counter",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(errorCount{pod=~\"$pod\"}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Time Requests",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(time_requests_bucket{pod=~\"$pod\"}[1m])) by (le))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Success Counter",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(successCount{pod=~\"$pod\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Process Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{service=\"au-data-quality\",pod=~\"$pod\"}",
     "legendFormat": "resident"
    },
    {
     "expr": "process_virtual_memory_bytes{service=\"au-data-quality\",pod=~\"$pod\"}",
     "legendFormat": "virtual"
    }
   ]
  },
  {
   "title": "Memstats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{service=\"au-data-quality\",pod=~\"$pod\"}",
     "legendFormat": "bytes allocates"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{service=\"au-data-quality\",pod=~\"$pod\"}",
     "legendFormat": "stack inuse"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{service=\"au-data-quality\",pod=~\"$pod\"}",
     "legendFormat": "heap inuse"
    }
   ]
  },
  {
   "title": "GC duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(go_gc_duration_seconds{service=\"au-data-quality\",pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Go Routines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{service=\"au-data-quality\",pod=~\"$pod\"}",
     "legendFormat": "resident"
    }
   ]
  }
 ]
}