{
 "title": "au-formula",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(CheckRuleCount, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Запрос всех измерений, ms",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(time_getAllMeasurement_bucket{pod=~\"$pod\"}[1m])) by (service,le))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Кол-во проверенных условий",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(CheckRuleCount{pod=~\"$pod\"}[1m])",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Проверка всех условий, ms",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(time_testAllFormula_bucket{pod=~\"$pod\"}[1m])) by (service,le))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Запрос условий проверки, ms",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(time_getSERules_bucket{pod=~\"$pod\"}[1m])) by (service,le))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Process Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{service=\"au-formula\",pod=~\"$pod\"}",
     "legendFormat": "resident by {{pod}}"
    },
    {
     "expr": "process_virtual_memory_bytes{service=\"au-formula\",pod=~\"$pod\"}",
     "legendFormat": "virtual by {{pod}}"
    }
   ]
  },
  {
   "title": "Memstats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{service=\"au-formula\",pod=~\"$pod\"}",
     "legendFormat": "bytes allocates"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{service=\"au-formula\",pod=~\"$pod\"}",
     "legendFormat": "stack inuse"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{service=\"au-formula\",pod=~\"$pod\"}",
     "legendFormat": "heap inuse"
    }
   ]
  },
  {
   "title": "GC duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(go_gc_duration_seconds{service=\"au-formula\",pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Go Routines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{service=\"au-formula\",pod=~\"$pod\"}",
     "legendFormat": "routines by {{pod}}"
    }
   ]
  }
 ]
}