{
 "title": "au-nsi",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "stc",
    "label": "Status Code",
    "query": "label_values(http_requests_bucket, status_code)"
   },
   {
    "name": "mtd",
    "label": "Method",
    "query": "label_values(http_requests_bucket, method)"
   },
   {
    "name": "type",
    "label": "DB Query type",
    "query": "label_values(db_queries_bucket, type)"
   }
  ]
 },
 "panels": [
  {
   "title": "HTTP Request",
   "type": "graph",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_bucket{method=~\"$mtd\",status_code=~\"$stc\"}[1m])) by (method,status_code)",
     "legendFormat": "{{method}} / {{status_code}}"
    }
   ]
  },
  {
   "title": "HTTP Request",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(db_queries_bucket{type=~\"$type\"}[1m])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Query Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(db_queries_count{type=~\"$type\"}[1m])",
     "legendFormat": "Count by {{type}}/{{pod}}"
    }
   ]
  },
  {
   "title": "HTTP Request sum/count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_requests_sum{method=~\"$mtd\"}[1m])",
     "legendFormat": "Sum by {{method}}/{{status_code}} - {{pod}}"
    },
    {
     "expr": "rate(http_requests_count{method=~\"$mtd\"}[1m])",
     "legendFormat": "Count by {{method}}/{{status_code}} - {{pod}}"
    }
   ]
  },
  {
   "title": "Query Sum",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(db_queries_sum{type=~\"$type\"}[1m])",
     "legendFormat": "Sum by {{type}}"
    }
   ]
  }
 ]
}