{
 "title": "au-router",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(request_processing_time_in_dq_ms_bucket, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Total processing time, ms",
   "type": "graph",
   "gridPos": { "h": 14, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(total_processing_time_in_ms_bucket{pod=~\"$pod\"}[1m])) by (pod,le))",
     "legendFormat": "99 quantile {{pod}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(total_processing_time_in_ms_bucket{pod=~\"$pod\"}[1m])) by (pod,le))",
     "legendFormat": "95 quantile {{pod}}"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(total_processing_time_in_ms_bucket{pod=~\"$pod\"}[1m])) by (pod,le))",
     "legendFormat": "50 quantile {{pod}}"
    },
    {
     "expr": "(rate(total_processing_time_in_ms_sum{pod=~\"$pod\"}[1m])) / (rate(total_processing_time_in_ms_count{pod=~\"$pod\"}[1m]))",
     "legendFormat": "sum/count by {{pod}}"
    }
   ]
  },
  {
   "title": "Request in DQ processing time, ms",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(request_processing_time_in_dq_ms_bucket{pod=~\"$pod\"}[1m])) by (pod,le))",
     "legendFormat": "95 {{pod}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(request_processing_time_in_dq_ms_bucket{pod=~\"$pod\"}[1m])) by (pod,le))",
     "legendFormat": "99 {{pod}}"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(request_processing_time_in_dq_ms_bucket{pod=~\"$pod\"}[1m])) by (pod,le))",
     "legendFormat": "50 {{pod}}"
    },
    {
     "expr": "(rate(request_processing_time_in_dq_ms_sum{pod=~\"$pod\"}[1m])) / (rate(request_processing_time_in_dq_ms_count{pod=~\"$pod\"}[1m]))",
     "legendFormat": "sum/count by {{pod}}"
    }
   ]
  },
  {
   "title": "Request in DQ processing time, ms",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(request_processing_time_in_tsdb_processed_ms_bucket{pod=~\"$pod\"}[1m])) by (pod,le))",
     "legendFormat": "95 {{pod}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(request_processing_time_in_tsdb_processed_ms_bucket{pod=~\"$pod\"}[1m])) by (pod,le))",
     "legendFormat": "99 {{pod}}"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(request_processing_time_in_tsdb_processed_ms_bucket{pod=~\"$pod\"}[1m])) by (pod,le))",
     "legendFormat": "50 {{pod}}"
    },
    {
     "expr": "(rate(request_processing_time_in_tsdb_processed_ms_sum{pod=~\"$pod\"}[1m])) / (rate(request_processing_time_in_tsdb_processed_ms_count{pod=~\"$pod\"}[1m]))",
     "legendFormat": "sum/count by {{pod}}"
    }
   ]
  },
  {
   "title": "Request in LFO processing time, ms",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(request_processing_time_in_lfo_ms_bucket{pod=~\"$pod\"}[1m])) by (pod,le))",
     "legendFormat": "95 {{pod}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(request_processing_time_in_lfo_ms_bucket{pod=~\"$pod\"}[1m])) by (pod,le))",
     "legendFormat": "99 {{pod}}"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(request_processing_time_in_lfo_ms_bucket{pod=~\"$pod\"}[1m])) by (pod,le))",
     "legendFormat": "50 {{pod}}"
    },
    {
     "expr": "(rate(request_processing_time_in_lfo_ms_sum{pod=~\"$pod\"}[1m])) / (rate(request_processing_time_in_lfo_ms_count{pod=~\"$pod\"}[1m]))",
     "legendFormat": "sum/count by {{pod}}"
    }
   ]
  },
  {
   "title": "Request in DQ processing time, ms",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(request_processing_time_in_dq_ms_bucket{pod=~\"$pod\"}[1m])) by (pod,le))",
     "legendFormat": "95 {{pod}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(request_processing_time_in_dq_ms_bucket{pod=~\"$pod\"}[1m])) by (pod,le))",
     "legendFormat": "99 {{pod}}"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(request_processing_time_in_dq_ms_bucket{pod=~\"$pod\"}[1m])) by (pod,le))",
     "legendFormat": "50 {{pod}}"
    },
    {
     "expr": "(rate(request_processing_time_in_dq_ms_sum{pod=~\"$pod\"}[1m])) / (rate(request_processing_time_in_dq_ms_count{pod=~\"$pod\"}[1m]))",
     "legendFormat": "sum/count by {{pod}}"
    }
   ]
  },
  {
   "title": "Process Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{service=\"au-router\",pod=~\"$pod\"}",
     "legendFormat": "resident"
    }
   ]
  },
  {
   "title": "Memstats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{service=\"au-router\",pod=~\"$pod\"}",
     "legendFormat": "bytes allocates"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{service=\"au-router\",pod=~\"$pod\"}",
     "legendFormat": "stack inuse"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{service=\"au-router\",pod=~\"$pod\"}",
     "legendFormat": "heap inuse"
    }
   ]
  },
  {
   "title": "Go Routines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{service=\"au-router\",pod=~\"$pod\"}",
     "legendFormat": "resident"
    }
   ]
  },
  {
   "title": "GC duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(go_gc_duration_seconds{service=\"au-router\",pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}