{
 "title": "au-soap-export",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "WSDL requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(wsdl_requests_counter[1m])",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Fetch Data Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(tsdb_fetch_data_time_bucket[1m])) by (le,service))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Fetch Data Time Counter",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(tsdb_fetch_data_time_count[1m])",
     "legendFormat": "{{service}}"
    }
   ]
  }
 ]
}