{
 "title": "au-tsdb",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Количество запросов на Чтение из TSDB",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(ctrl_reads_count[1m])", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "Количество запросов на запись в TSDB",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(ctrl_writes_count[1m])", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "Длительность запроса на чтение, ms",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(ctrl_reads_bucket[5m])) by (pod,le))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Длительность запроса на запись, ms",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(ctrl_writes_bucket[5m])) by (pod,le))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Redis Reads Count",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(redis_reads_count[1m])", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "Redis Writes Count",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(redis_writes_count[1m])", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "Redis Reads Duration, ms",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(redis_reads_bucket[5m])) by (pod,le))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Redis Writes Duration, ms",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(redis_writes_bucket[5m])) by (pod,le))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "ClickHouse Reads Count",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(clickhouse_reads_count[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "ClickHouse Writes Count",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(clickhouse_writes_count[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "ClickHouse Reads Duration, ms",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(clickhouse_reads_bucket[5m])) by (pod,le))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "ClickHouse Writes Duration, ms",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(clickhouse_writes_bucket{}[5m])) by (pod,le))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Redis Values Counter",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(redis_values_in[1m])", "legendFormat": "In {{pod}}" },
    { "expr": "rate(redis_values_out[1m])", "legendFormat": "Out {{pod}}" }
   ]
  },
  {
   "title": "DB Values Counter",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(db_values_in[1m])", "legendFormat": "In {{pod}}" },
    { "expr": "rate(db_values_out[1m])", "legendFormat": "Out {{pod}}" }
   ]
  },
  {
   "title": "DB Rows Counter",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(db_rows_in[1m])", "legendFormat": "In {{pod}}" }
   ]
  },
  {
   "title": "Error 400",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(errors_400[1m])", "legendFormat": "Error 400 {{pod}}" }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cpu_user{service=\"au-tsdb\"}",
     "legendFormat": "CPU user {{pod}}"
    },
    {
     "expr": "cpu_system{service=\"au-tsdb\"}",
     "legendFormat": "CPU system {{pod}}"
    }
   ]
  },
  {
   "title": "Garbage Collector, ms",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 20 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(gc_main_bucket[5m])) by (pod,le))",
     "legendFormat": "Main by {{pod}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(gc_worker_bucket[5m])) by (pod,le))",
     "legendFormat": "Worker by {{pod}}"
    }
   ]
  },
  {
   "title": "Event Loop, ms",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "event_loop_delay_main", "legendFormat": "Main by {{pod}}" },
    { "expr": "event_loop_delay_worker", "legendFormat": "Worker by {{pod}}" }
   ]
  },
  {
   "title": "Error 500",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(errors_500[1m])", "legendFormat": "Error 500 {{pod}}" }
   ]
  }
 ]
}