{
 "title": "ClickHouse Dashboard",
 "description": "Clickhouse",
 "tags": [
  "clickhouse",
  "operator"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(ClickHouseAsyncMetrics_Uptime, namespace)"
   },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(ClickHouseAsyncMetrics_Uptime, job)"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "table",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "ClickHouseAsyncMetrics_Uptime{namespace=~\"$namespace\",job=~\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "CPU-core Usage, %",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container=\"au-tsdb-clickhouse\",service=\"mon-prometheus-operator-kubelet\"}[5m])*100",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Queris, per second",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ClickHouseProfileEvents_Query\r{namespace=~\"$namespace\",job=~\"$job\"}[1m])",
     "legendFormat": "Query {{job}}"
    },
    {
     "expr": "rate(ClickHouseProfileEvents_SelectQuery\r{namespace=~\"$namespace\",job=~\"$job\"}[1m])",
     "legendFormat": "SelectQuery {{job}}"
    },
    {
     "expr": "rate(ClickHouseProfileEvents_InsertQuery\r{namespace=~\"$namespace\",job=~\"$job\"}[1m])",
     "legendFormat": "InsertQuery {{job}}"
    }
   ]
  },
  {
   "title": "Open Files",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ClickHouseProfileEvents_FileOpen\r{namespace=~\"$namespace\",job=~\"$job\"}[1m])",
     "legendFormat": "Open files by {{job}}"
    }
   ]
  },
  {
   "title": "Version",
   "type": "table",
   "description": "For example, version 11.22.33 is translated to 11022033",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "ClickHouseMetrics_VersionInteger{namespace=~\"$namespace\",job=~\"$job\"}",
     "legendFormat": "Version: {{job}}"
    },
    {
     "expr": "ClickHouseMetrics_Revision\r{namespace=~\"$namespace\",job=~\"$job\"}",
     "legendFormat": "Revision {{job}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{container=\"au-tsdb-clickhouse\",service=\"mon-prometheus-operator-kubelet\"}",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Read Descriptor",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 10, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(ClickHouseProfileEvents_ReadBufferFromFileDescriptorReadBytes\r{namespace=~\"$namespace\",job=~\"$job\"}[1m])",
     "legendFormat": "descriptor bytes by {{job}}"
    },
    {
     "expr": "rate(ClickHouseProfileEvents_ReadBufferFromFileDescriptorRead\r{namespace=~\"$namespace\",job=~\"$job\"}[1m])",
     "legendFormat": "descriptor by {{job}}"
    }
   ]
  },
  {
   "title": "Compressed Read Buffer",
   "type": "graph",
   "description": "Show how much bytes read and decompress via compressed buffer on each server in cluster",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(ClickHouseProfileEvents_CompressedReadBufferBytes{namespace=~\"$namespace\",job=~\"$job\"}[1m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "r/w Failed",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ClickHouseProfileEvents_WriteBufferFromFileDescriptorWriteFailed\r{namespace=~\"$namespace\",job=~\"$job\"}[1m])",
     "legendFormat": "Write Failed by {{job}}"
    },
    {
     "expr": "rate(ClickHouseProfileEvents_ReadBufferFromFileDescriptorReadFailed{namespace=~\"$namespace\",job=~\"$job\"}\r[1m])",
     "legendFormat": "Read Failed by {{job}}"
    }
   ]
  },
  {
   "title": "Jemalloc",
   "type": "graph",
   "description": "Show jemalloc memory distribution",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ClickHouseAsyncMetrics_jemalloc_mapped\r{namespace=~\"$namespace\",job=~\"$job\"}",
     "legendFormat": "mapped {{job}}"
    },
    {
     "expr": "ClickHouseAsyncMetrics_jemalloc_resident\r{namespace=~\"$namespace\",job=~\"$job\"}",
     "legendFormat": "resident {{job}}"
    },
    {
     "expr": "ClickHouseAsyncMetrics_jemalloc_retained\r{namespace=~\"$namespace\",job=~\"$job\"}",
     "legendFormat": "retained {{job}}"
    },
    {
     "expr": "ClickHouseAsyncMetrics_jemalloc_active\r{namespace=~\"$namespace\",job=~\"$job\"}",
     "legendFormat": "active {{job}}"
    },
    {
     "expr": "ClickHouseAsyncMetrics_jemalloc_allocated\r{namespace=~\"$namespace\",job=~\"$job\"}",
     "legendFormat": "allocated {{job}}"
    },
    {
     "expr": "ClickHouseAsyncMetrics_jemalloc_metadata\r{namespace=~\"$namespace\",job=~\"$job\"}",
     "legendFormat": "metadata {{job}}"
    }
   ]
  },
  {
   "title": "Write Descriptor",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 10, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(ClickHouseProfileEvents_WriteBufferFromFileDescriptorWriteBytes\r{namespace=~\"$namespace\",job=~\"$job\"}[1m])",
     "legendFormat": "descriptor bytes by {{job}}"
    },
    {
     "expr": "rate(ClickHouseProfileEvents_WriteBufferFromFileDescriptorWrite{namespace=~\"$namespace\",job=~\"$job\"}\r[1m])",
     "legendFormat": "descriptor by {{job}}"
    }
   ]
  },
  {
   "title": "Marks Cache Hit Rate",
   "type": "graph",
   "description": "Show which percent of mark files (.mrk) read from memory instead of disk",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 10 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(ClickHouseProfileEvents_MarkCacheHits{namespace=~\"$namespace\",job=~\"$job\"}[1m]) / (rate(ClickHouseProfileEvents_MarkCacheHits{namespace=~\"$namespace\",job=~\"$job\"}[1m]) + rate(ClickHouseProfileEvents_MarkCacheMisses{namespace=~\"$namespace\",job=~\"$job\"}[1m]))",
     "legendFormat": "1m {{job}}"
    }
   ]
  },
  {
   "title": "Page Fault",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ClickHouseProfileEvents_HardPageFaults{namespace=~\"$namespace\",job=~\"$job\"}[5m])",
     "legendFormat": "Hard by {{job}}"
    },
    {
     "expr": "rate(ClickHouseProfileEvents_SoftPageFaults\r{namespace=~\"$namespace\",job=~\"$job\"}[1m])",
     "legendFormat": "Soft by {{job}}"
    }
   ]
  },
  {
   "title": "Merge",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 10, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ClickHouseProfileEvents_MergedRows{namespace=~\"$namespace\",job=~\"$job\"}[1m])",
     "legendFormat": "MergedRows by {{job}}"
    },
    {
     "expr": "rate(ClickHouseProfileEvents_MergedUncompressedBytes{namespace=~\"$namespace\",job=~\"$job\"}[1m])",
     "legendFormat": "MergedUncompressedBytes by {{job}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "description": "Show different types of connections for each server",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ClickHouseMetrics_TCPConnection{namespace=~\"$namespace\",job=~\"$job\"}",
     "legendFormat": "tcp {{job}}"
    },
    {
     "expr": "ClickHouseMetrics_HTTPConnection{namespace=~\"$namespace\",job=~\"$job\"}",
     "legendFormat": "http {{job}}"
    },
    {
     "expr": "ClickHouseMetrics_InterserverConnection{namespace=~\"$namespace\",job=~\"$job\"}",
     "legendFormat": "interserver {{job}}"
    },
    {
     "expr": "ClickHouseMetrics_MySQLConnection{namespace=~\"$namespace\",job=~\"$job\"}",
     "legendFormat": "mysql {{job}}"
    }
   ]
  }
 ]
}