{
 "title": "au-data-receiver",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "srv",
    "label": "Service",
    "query": "label_values(frames_total, service)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(frames_total, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Packets received",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(frames_total{endpoint=\"http\",service=~\"$srv\",pod=~\"$pod\"}[1m])",
     "legendFormat": "{{service}} / pod : {{pod}}"
    }
   ]
  },
  {
   "title": "Packets dropped",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(dropped_total{endpoint=\"http\",service=~\"$srv\",pod=~\"$pod\"}[1m])",
     "legendFormat": "{{service}} / pod : {{pod}}"
    }
   ]
  },
  {
   "title": "Process Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{service=~\"$srv\",pod=~\"$pod\"}",
     "legendFormat": "resident by {{pod}}"
    },
    {
     "expr": "process_virtual_memory_bytes{service=~\"$srv\",pod=~\"$pod\"}",
     "legendFormat": "virtual by {{pod}}"
    }
   ]
  },
  {
   "title": "Memstats",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{service=~\"$srv\",pod=~\"$pod\"}",
     "legendFormat": "bytes allocates {{pod}} / {{service}}"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{service=~\"$srv\",pod=~\"$pod\"}",
     "legendFormat": "stack inuse {{pod}} / {{service}}"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{service=~\"$srv\",pod=~\"$pod\"}",
     "legendFormat": "heap inuse {{pod}} / {{service}}"
    }
   ]
  },
  {
   "title": "GC duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(go_gc_duration_seconds{service=~\"$srv\",pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Go Routines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{service=~\"$srv\",pod=~\"$pod\"}",
     "legendFormat": "routines by {{pod}} / {{service}}"
    }
   ]
  }
 ]
}