{
 "title": "Redis Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(redis_up, namespace)"
   },
   { "name": "job_name", "label": "JOB", "query": "label_values(redis_up, job)" }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "table",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "redis_uptime_in_seconds{job=~\"$job_name\",namespace=~\"$namespace\"}",
     "legendFormat": "uptime by {{job}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 5, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(redis_cpu_sys_seconds_total{job=~\"$job_name\",namespace=~\"$namespace\"}[5m])*100",
     "legendFormat": "CPU Usage by {{pod}}"
    }
   ]
  },
  {
   "title": "Commands",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(redis_commands_processed_total{job=~\"$job_name\",namespace=~\"$namespace\"}[5m])",
     "legendFormat": "by {{pod}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "redis_connected_clients{job=~\"$job_name\",namespace=~\"$namespace\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 5, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "redis_memory_used_bytes{job=~\"$job_name\",namespace=~\"$namespace\"}",
     "legendFormat": "Used Bytes by {{pod}}"
    }
   ]
  },
  {
   "title": "Hits/Misses",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(redis_keyspace_hits_total{job=~\"$job_name\",namespace=~\"$namespace\"}[5m])",
     "legendFormat": "Hits by {{pod}}"
    },
    {
     "expr": "irate(redis_keyspace_misses_total{job=~\"$job_name\",namespace=~\"$namespace\"}[5m])",
     "legendFormat": "Misses by {{pod}}"
    }
   ]
  },
  {
   "title": "Network Rx/Tx",
   "type": "graph",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(redis_net_input_bytes_total{job=~\"$job_name\",namespace=~\"$namespace\"}[5m])",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "rate(redis_net_output_bytes_total{job=~\"$job_name\",namespace=~\"$namespace\"}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Total Items per DB",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 5, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (redis_db_keys{job=~\"$job_name\",namespace=~\"$namespace\"}) by (db)",
     "legendFormat": "{{db}}"
    }
   ]
  },
  {
   "title": "Expiring vs No-expiring Keys",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (redis_db_keys{job=~\"$job_name\",namespace=~\"$namespace\"}) - sum (redis_db_keys_expiring{job=~\"$job_name\",namespace=~\"$namespace\"}) ",
     "legendFormat": "Not expiring"
    },
    {
     "expr": "sum (redis_db_keys_expiring{job=~\"$job_name\",namespace=~\"$namespace\"}) ",
     "legendFormat": "Expiring"
    }
   ]
  }
 ]
}